# Урок 2

# Матрицы и матричные операции. Часть 1

### __1.__  Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

### а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
### б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
### в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
### г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.


### __Решение:__

### а)

$AB$ - не определено, так как число столбцов матрицы $A$ не равно числу строк матрицы $B\,(2\neq4)$.

$BA$ - не определено, так как число столбцов матрицы $B$ не равно числу строк матрицы $A\,(2\neq4)$.

### б)

$AB$ - определено, так как число столбцов матрицы $A$ не равно числу строк матрицы $B\,(5=5)$. Размерность полученной матрицы $2\times 3$.

$BA$ - не определено, так как число столбцов матрицы $B$ не равно числу строк матрицы $A\,(3\neq2)$.

### в)

$AB$ - определено, так как число столбцов матрицы $A$ не равно числу строк матрицы $B\,(3=3)$. Размерность полученной матрицы $8\times 8$.

$BA$ - определено, так как число столбцов матрицы $B$ не равно числу строк матрицы $A\,(8=8)$. Размерность полученной матрицы $3\times 3$.

### г)

$AB$ - определено, так как число столбцов матрицы $A$ не равно числу строк матрицы $B\,(4=4)$. Размерность полученной матрицы $4\times 4$.

$BA$ - определено, так как число столбцов матрицы $B$ не равно числу строк матрицы $A\,(4=4)$. Размерность полученной матрицы $4\times 4$.

### __Ответ:__

### а) $AB$ - не определено, $BA$ - не определено;
### б) $AB$ - определено $2\times 3$, $BA$ - не определено;
### в) $AB$ - определено $8\times 8$, $BA$ - определено $3\times 3$;
### г) $AB$ - определено $4\times 4$, $BA$ - определено $4\times 4$.


### __2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$


### __Решение:__

$$\begin{pmatrix}
1 & -2\\ 
3 & 0 
\end{pmatrix} + \begin{pmatrix}
4 & -1\\ 
0 & 5 
\end{pmatrix} = \begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}.$$

In [1]:
import numpy as np

In [2]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

print(f'Матрица A\n{A}\n')
print(f'Матрица B\n{B}\n')
print(f'Матрица A + B\n{A + B}')

Матрица A
[[ 1 -2]
 [ 3  0]]

Матрица B
[[ 4 -1]
 [ 0  5]]

Матрица A + B
[[ 5 -3]
 [ 3  5]]


$$A\cdot B=\begin{pmatrix}
1\cdot4-2\cdot0 & 1\cdot-1-2\cdot5\\ 
3\cdot4+0\cdot0 & 3\cdot-1+0\cdot5
\end{pmatrix}=\begin{pmatrix}
4 & -11\\
12 & -3
\end{pmatrix}.$$

In [3]:
print(f'Матрица AB\n{np.dot(A, B)}')

Матрица AB
[[  4 -11]
 [ 12  -3]]


$$B\cdot A=\begin{pmatrix}
4\cdot1-1\cdot3 & 4\cdot-2-1\cdot0\\ 
0\cdot1+5\cdot3 & 0\cdot-2+5\cdot0
\end{pmatrix}=\begin{pmatrix}
1 & -8\\
15 & 0
\end{pmatrix}.$$

In [4]:
print(f'Матрица BA\n{np.dot(B, A)}')

Матрица BA
[[ 1 -8]
 [15  0]]


### __Ответ:__ $A+B=\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$; $AB=\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}$; $BA=\begin{pmatrix}
1 & -8\\ 
15 & 0
\end{pmatrix}$

### __3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

### __Решение:__

$$3A=3\cdot\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}=\begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix}$$

$$-2B=-2\cdot\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}=\begin{pmatrix}
0 & -10\\ 
-4 & 2
\end{pmatrix}$$

$$4C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}=\begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix}$$

$$3A-2B+4C=\begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix}+\begin{pmatrix}
0 & -10\\ 
-4 & 2
\end{pmatrix}+\begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix}=\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$$

In [5]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

print(f'Матрица A\n{A}\n')
print(f'Матрица B\n{B}\n')
print(f'Матрица С\n{C}\n')
print(f'Матрица 3A-2B+4C\n{3*A - 2*B + 4*C}')


Матрица A
[[ 1  7]
 [ 3 -6]]

Матрица B
[[ 0  5]
 [ 2 -1]]

Матрица С
[[ 2 -4]
 [ 1  1]]

Матрица 3A-2B+4C
[[ 11  -5]
 [  9 -12]]


### __Ответ:__ $\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$

### __4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$. Вычислить $AA^{T}$ и $A^{T}A$.

### __Решение:__

$$A^{T}=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}$$

$$AA^{T}=\begin{pmatrix}
4\cdot4+1\cdot1 & 4\cdot5+1\cdot-2 & 4\cdot2+1\cdot3\\ 
5\cdot4-2\cdot1 & 5\cdot5-2\cdot-2 & 5\cdot2-2\cdot3\\ 
2\cdot4+3\cdot1 & 2\cdot5+3\cdot-2 & 2\cdot2+3\cdot3
\end{pmatrix}=\begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\ 
11 & 4 & 13
\end{pmatrix}$$

In [6]:
A = np.array([[4, 1], [5, -2], [2, 3]])

print(f'Матрица A\n{A}\n')

AT=A.T

print(f'Матрица A^T\n{AT}\n')

print(f'Матрица A*A^T\n{A.dot(AT)}\n')


Матрица A
[[ 4  1]
 [ 5 -2]
 [ 2  3]]

Матрица A^T
[[ 4  5  2]
 [ 1 -2  3]]

Матрица A*A^T
[[17 18 11]
 [18 29  4]
 [11  4 13]]



$$A^{T}A=\begin{pmatrix}
4\cdot4+5\cdot5+2\cdot2 & 4\cdot1+5\cdot-2+2\cdot3\\ 
1\cdot4-2\cdot5+3\cdot2 & 1\cdot1-2\cdot-2+3\cdot3\
\end{pmatrix}=\begin{pmatrix}
45 & 0\\ 
0 & 14
\end{pmatrix}$$

In [7]:
print(f'Матрица A^T*A\n{AT.dot(A)}\n')


Матрица A^T*A
[[45  0]
 [ 0 14]]



### __Ответ:__ $\begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\ 
11 & 4 & 13
\end{pmatrix}$; $\begin{pmatrix}
45 & 0\\ 
0 & 14
\end{pmatrix}$.

### __5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

### __Решение:__

In [8]:
def multmatrix(A, B):
    if len(A[0]) != len(B):
        raise ValueError('Произведение не определено!')
    result = np.zeros((len(A), len(B[0])), int)
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                result[i][j] += A[i][k] * B[k][j]
    return result
    
A = np.array([[4, 1], [5, -2], [2, 3]])
B = np.array([[4, 1, 5], [-2, 2, 3]])
print(f'Матрица A\n{A}\n')
print(f'Матрица B\n{B}\n')

print(f'Наш алгоритм: Матрица AB\n{multmatrix(A, B)}\n')

print(f'Numpy алгоритм: Матрица AB\n{np.dot(A,B)}\n')

Матрица A
[[ 4  1]
 [ 5 -2]
 [ 2  3]]

Матрица B
[[ 4  1  5]
 [-2  2  3]]

Наш алгоритм: Матрица AB
[[14  6 23]
 [24  1 19]
 [ 2  8 19]]

Numpy алгоритм: Матрица AB
[[14  6 23]
 [24  1 19]
 [ 2  8 19]]

