# Урок 2

# Матрицы и матричные операции. Часть 2

### __1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

### __Решение:__

### а)

$$\begin{vmatrix}
\sin x & -\cos x\\ 
\cos x & \sin x
\end{vmatrix}=\sin x\cdot\sin x + \cos x\cdot\cos x=\sin^{2}x+\cos^{2}x=1$$

### б)

$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix}=4\cdot\begin{vmatrix}
5 & 1\\ 
0 & 9
\end{vmatrix}-2\cdot\begin{vmatrix}
0 & 1\\ 
0 & 9
\end{vmatrix}+3\cdot\begin{vmatrix}
0 & 5 \\ 
0 & 0
\end{vmatrix}=4\cdot45-2\cdot0+3\cdot0=180$$

In [1]:
import numpy as np
A = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'Матрица:\n{A}')
print(f'Определитель:\n{np.linalg.det(A):.0f}')

Матрица:
[[4 2 3]
 [0 5 1]
 [0 0 9]]
Определитель:
180


### в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}=1\cdot\begin{vmatrix}
5 & 6\\ 
8 & 9
\end{vmatrix}-2\cdot\begin{vmatrix}
4 & 6\\ 
7 & 9
\end{vmatrix}+3\cdot\begin{vmatrix}
4 & 5\\ 
7 & 8
\end{vmatrix}=1\cdot-3-2\cdot-6+3\cdot-3=0$$

In [2]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Матрица:\n{A}')
print(f'Определитель:\n{np.linalg.det(A):.0f}')

Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель:
0


### __Ответ:__ а) $1$; б) $180$; в) $0$.

### __2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.


### __Решение:__

Согласно свойствам определителя:

### а)

__9.__ Для двух квадратных матриц одинакового размера

$$det(AB)=detA\cdot detB.$$

Искомое значение:

$$det(A^2)=det(A\cdot A)=detA\cdot detA =16.$$

### б)

__1.__ Определитель транспонированной матрицы равен определителю исходной:

$$detA^{T}=detA.$$

Искомое значение:

$$det(A^{T})=detA=4.$$

### в)

__2.__ Умножение строки или столбца матрицы на число $\lambda$ приведет к умножению определителя матрицы на то же число. 

Так как умножение матрицы $A$ на число 2 приводит к умножению каждой строки матрицы на число 2, то искомое значение:

$$det(2A)=2^n\cdot detA=2^n\cdot4,$$

где $n$ - это порядок исходной квадратной матрицы.

### __Ответ:__ а) $16$; б) $4$ ; в) $2^n\cdot4$, где $n$ - порядок исходной квадратной матрицы.

### __3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

### __Решение:__

Заметим, что вторая строка может быть получена путём умножения первой строки на $-2$.

Согласно свойствам определителя:

__6.__ Если две строки (столбца) матрицы линейно зависимы, то определитель этой матрицы равен нулю.

Т.к. определитель равен нулю, то матрица вырожденная.

In [3]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Матрица:\n{A}')
print(f'Определитель:\n{np.linalg.det(A):.0f}')

Матрица:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]
Определитель:
0


### __4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

### __Решение:__

### а)

Из второй и третьей строк вычтем первую, умноженную на $1$ и $2$ соответственно:

$$\begin{pmatrix}
1 & 2 & 3\\ 
0 & -1 & -2\\ 
0 & -1 & -2
\end{pmatrix}.$$

Вторая и третья строки равны, отбрасываем третью:

$$\begin{pmatrix}
1 & 2 & 3\\ 
0 & -1 & -2
\end{pmatrix}.$$

Таким образом, ранг матрицы равен $2$.

In [4]:
A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
r = np.linalg.matrix_rank(A)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 2


### б)

Переставим четвертую строку на первую:

$$\begin{pmatrix}
2 & 3 & 5 & 6\\
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3 
\end{pmatrix}.$$

Из третьей и четвертой строк вычтем вторую, умноженную на  1  и  2  соответственно:

$$\begin{pmatrix}
2 & 3 & 5 & 6\\
0 & 0 & 2 & 1\\ 
0 & 0 & 0 & 1\\ 
0 & 0 & 0 & 1 
\end{pmatrix}.$$

Третья и четвертая строки равны, отбрасываем четвертую:

$$\begin{pmatrix}
2 & 3 & 5 & 6\\
0 & 0 & 2 & 1\\ 
0 & 0 & 0 & 1
\end{pmatrix}.$$

Таким образом, ранг матрицы равен $3$.

In [5]:
A = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
r = np.linalg.matrix_rank(A)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 3


### __Ответ:__ а) $2$; б) $3$.

### __5*.__ Написать на Python функцию вычисления определителя методом разложения матрицы.

### __Решение:__

In [6]:
def getMinors(A):
    result = []
    for j in range(len(A[0])):
        _split = np.hsplit(A[1:,],(j,j+1))
        result.append(np.hstack((_split[0], _split[2])))
    return result

def getDet(A):
    result = 0
    if len(A) < 3:
        result = A[0,0]*A[1,1]-A[0,1]*A[1,0]
    else:
        M = getMinors(A)
        for num,item in enumerate(M):
            if A[0,num] > 0:
                result += A[0,num]*(-1)**num*getDet(item)
    return result
        
    
A = np.array([[1, 0, 3, 1, 1], [4, 5, 6, 1, -1], [7, 8, 2, 1, 8], [7, 7, 2, 1, 2], [1, 0, 3, 1, 7]])
print(f'Матрица A\n{A}\n')

B = A.T
print(f'Матрица B\n{B}\n')

print(f'Наш алгоритм: определитель A\n{getDet(A)}\n')
print(f'Numpy алгоритм: определитель A\n{np.linalg.det(A)}\n')

print(f'Наш алгоритм: определитель B\n{getDet(B)}\n')
print(f'Numpy алгоритм: определитель B\n{np.linalg.det(B)}\n')

Матрица A
[[ 1  0  3  1  1]
 [ 4  5  6  1 -1]
 [ 7  8  2  1  8]
 [ 7  7  2  1  2]
 [ 1  0  3  1  7]]

Матрица B
[[ 1  4  7  7  1]
 [ 0  5  8  7  0]
 [ 3  6  2  2  3]
 [ 1  1  1  1  1]
 [ 1 -1  8  2  7]]

Наш алгоритм: определитель A
126

Numpy алгоритм: определитель A
125.99999999999989

Наш алгоритм: определитель B
126

Numpy алгоритм: определитель B
126.0

