# Урок 4

# Системы линейных уравнений. Часть 1

### __1.__ Решить систему уравнений методом Гаусса:

### $$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

### __Решение:__

Запишем расширенную матрицу системы:

### $$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
2 & 1 & -1 & 1 \\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$$

Путем элементарных преобразований постараемся привести матрицу к ступенчатому виду.

Вычтем из второй строки первую, умноженную на 2:

### $$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -1 & 1 & 5 \\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$$

Вычтем из третьей строки первую:

### $$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -1 & 1 & 5 \\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$$

### $$x_{4}=c,$$
### $$-2x_{3}+3c=4 \; \Leftrightarrow \; x_{3}=(3c-4)/2,$$
### $$-x_{2} + (3c-4)/2 + 5c=-2 \; \Leftrightarrow \; x_{2}=13c/2,$$
### $$x_{1} + 13c/2 - (3c-4)/2 -2c=0 \; \Leftrightarrow \; x_{1}=-3c-2.$$


In [1]:
import numpy as np
A = np.array([[1, 1, -1, -2], [2, 1, -1, 1], [1, 1, -3, 1]])
b = np.array([[0, -2, 4]]).T
print(f'Матрица A:\n{A}')
print(f'b:\n{b}\n')

c = 0
x = np.array([[-3*c-2, 13*c/2, (3*c-4)/2, c]]).T
print(f'Частное решение при с={c}:\n{x}')

print(f'Ax:\n{A.dot(x)}=b')

c = 2
x = np.array([[-3*c-2, 13*c/2, (3*c-4)/2, c]]).T
print(f'Частное решение при с={c}:\n{x}')

print(f'Ax:\n{A.dot(x)}=b')

Матрица A:
[[ 1  1 -1 -2]
 [ 2  1 -1  1]
 [ 1  1 -3  1]]
b:
[[ 0]
 [-2]
 [ 4]]

Частное решение при с=0:
[[-2.]
 [ 0.]
 [-2.]
 [ 0.]]
Ax:
[[ 0.]
 [-2.]
 [ 4.]]=b
Частное решение при с=2:
[[-8.]
 [13.]
 [ 1.]
 [ 2.]]
Ax:
[[ 0.]
 [-2.]
 [ 4.]]=b


### __Ответ:__ система имеет множество решений вида $x=\begin{pmatrix}
-3c-2 \\ 
13c/2 \\
(3c-4)/2 \\
c \\
\end{pmatrix}$.

### __2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

###   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
###   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
###   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

### __Решение:__

### а)

In [2]:
A = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
A_= np.array([[3, -1, 1, 4], [2, -5, -3, -17], [1, 1, -1, 0]])

print(f'Матрица A:\n{A}')
print(f'Расширенная матрица A:\n{A_}\n')
print(f'Ранг матрицы А:\n{np.linalg.matrix_rank(A)}')
print(f'Ранг расширенной матрицы А:\n{np.linalg.matrix_rank(A_)}')

Матрица A:
[[ 3 -1  1]
 [ 2 -5 -3]
 [ 1  1 -1]]
Расширенная матрица A:
[[  3  -1   1   4]
 [  2  -5  -3 -17]
 [  1   1  -1   0]]

Ранг матрицы А:
3
Ранг расширенной матрицы А:
3


$rankA=rank \tilde A=3$, число неизвестных $n=3$, значит система определена, т. е. имеет единственное решение.

### б)

In [3]:
A = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
A_= np.array([[2, -4, 6, 1], [1, -2, 3, -2], [3, -6, 9, 5]])

print(f'Матрица A:\n{A}')
print(f'Расширенная матрица A:\n{A_}\n')
print(f'Ранг матрицы А:\n{np.linalg.matrix_rank(A)}')
print(f'Ранг расширенной матрицы А:\n{np.linalg.matrix_rank(A_)}')

Матрица A:
[[ 2 -4  6]
 [ 1 -2  3]
 [ 3 -6  9]]
Расширенная матрица A:
[[ 2 -4  6  1]
 [ 1 -2  3 -2]
 [ 3 -6  9  5]]

Ранг матрицы А:
1
Ранг расширенной матрицы А:
2


$rankA<rank \tilde A$, значит система несовместна.

### в)

In [4]:
A = np.array([[1, 2, 5], [3, 1, -8]])
A_ = np.array([[1, 2, 5, 4], [3, 1, -8, -2]])

print(f'Матрица A:\n{A}')
print(f'Расширенная матрица A:\n{A_}\n')
print(f'Ранг матрицы А:\n{np.linalg.matrix_rank(A)}')
print(f'Ранг расширенной матрицы А:\n{np.linalg.matrix_rank(A_)}')

Матрица A:
[[ 1  2  5]
 [ 3  1 -8]]
Расширенная матрица A:
[[ 1  2  5  4]
 [ 3  1 -8 -2]]

Ранг матрицы А:
2
Ранг расширенной матрицы А:
2


$rankA=rank \tilde A=2$, число неизвестных $n=3$, значит система имеет  бесконечное количество решений.

### __Ответ:__ а) совместна, решение единственное; б) несовместна; в) совместна, бесконечное количество решений.

### __3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

### $$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

### __Решение:__

In [5]:
A_ = np.array([[1, 3, -2, 4, 3], [0, 5, 0, 1, 2], [0, 0, 3, 0, 4], [0, 0, 0, 2, 1]])
A = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])

print(f'Расширенная матрица A:\n{A_}\n')
print(f'Матрица A:\n{A}')
print(f'Ранг матрицы А:\n{np.linalg.matrix_rank(A)}')
print(f'Ранг расширенной матрицы А:\n{np.linalg.matrix_rank(A_)}')

Расширенная матрица A:
[[ 1  3 -2  4  3]
 [ 0  5  0  1  2]
 [ 0  0  3  0  4]
 [ 0  0  0  2  1]]

Матрица A:
[[ 1  3 -2  4]
 [ 0  5  0  1]
 [ 0  0  3  0]
 [ 0  0  0  2]]
Ранг матрицы А:
4
Ранг расширенной матрицы А:
4


$rankA=rank \tilde A=4$, число неизвестных $n=4$, значит система определена, т. е. имеет единственное решение.

### __Ответ:__ совместна, решение единственное.

### __4.__ Дана система линейных уравнений, заданная расширенной матрицей

### $$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

### Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

### __Решение:__

Путем элементарных преобразований постараемся привести матрицу к ступенчатому виду.

Вычтем из второй строки первую, умноженную на 4:

### $$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b-4a\\
c
\end{matrix}
\end{pmatrix}.$$

Вычтем из третьей строки первую, умноженную на 7:

### $$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & -6 & -12
\end{matrix}\right|
\begin{matrix}
a\\ 
b-4a\\
c-7a
\end{matrix}
\end{pmatrix}.$$

Вычтем из третьей строки вторую, умноженную на 2:

### $$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b-4a\\
c-7a-2(b-4a)
\end{matrix}
\end{pmatrix}.$$

Если $c-7a-2(b-4a)=a-2b+c\neq 0$, то $rank \tilde A=3$, в то время как $rank A=2$. Это означает, что система в этом случае несовместна.

In [6]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(f'Матрица A:\n{A}')
print(f'Ранг матрицы А:\n{np.linalg.matrix_rank(A)}')

A_1 = np.array([[1, 2, 3, 1], [4, 5, 6, 1], [7, 8, 9, 1]])
print(f'Ранг матрицы А_ при a-2b+c=0:\n{np.linalg.matrix_rank(A_1)}')

A_2 = np.array([[1, 2, 3, 1], [4, 5, 6, -1], [7, 8, 9, 1]])
print(f'Ранг матрицы А_ при a-2b+c<>0:\n{np.linalg.matrix_rank(A_2)}')

Матрица A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Ранг матрицы А:
2
Ранг матрицы А_ при a-2b+c=0:
2
Ранг матрицы А_ при a-2b+c<>0:
3


### __Ответ:__ $a-2b+c\neq 0$.