# Урок 3

# Линейные преобразования

### Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

### $$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

### __Решение:__

Найдем собственные значения линейного оператора, составив и решив характеристическое уравнение:

### $$\begin{vmatrix}
-1-\lambda & -6\\ 
2 & 6-\lambda
\end{vmatrix} = 0,$$

### $$(-1-\lambda)(6-\lambda)+6\cdot2=0,$$

### $$\lambda^{2}-5\lambda+6=0,$$

### $$\lambda_1=3,\,\lambda_2=2$$

Теперь найдем собственные векторы вида $\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$, подставив полученное собственное значение в выражение $\textbf{A}x=\lambda x$:

### $$\begin{pmatrix}
a & b\\ 
c & d
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\lambda
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}.
$$

Получим

### $$\begin{cases}
ax_{1}+bx_{2}=\lambda x_{1}, \\
cx_{1}+dx_{2}=\lambda x_{2}.
\end{cases}$$ 

Для $\lambda_1=3$:

### $$\begin{cases}
-x_{1}-6x_{2}=3x_{1}, \\
2x_{1}+6x_{2}=3x_{2}.
\end{cases}$$

### $$\begin{cases}
-4x_{1}-6x_{2}=0, \\
2x_{1}-4x_{1}+2x_{1}=0;
\end{cases}$$

### $$\begin{cases}
-4x_{1}=6x_{2}, \\
0=0;
\end{cases}$$

Система имеет множество решений вида вида $x=\begin{pmatrix}
C\\ 
-\frac{2}{3}C
\end{pmatrix}$, следовательно собственному значению $\lambda_1=3$ соответствует множество собственных векторов $x=\begin{pmatrix}
C\\ 
-\frac{2}{3}C
\end{pmatrix}$, где $C\neq0$.

Для $\lambda_2=2$:

### $$\begin{cases}
-x_{1}-6x_{2}=2x_{1}, \\
2x_{1}+6x_{2}=2x_{2}.
\end{cases}$$

### $$\begin{cases}
-3x_{1}-6x_{2}=0, \\
2x_{1}-3x_{1}+x_{1}=0;
\end{cases}$$

### $$\begin{cases}
-3x_{1}=6x_{2}, \\
0=0;
\end{cases}$$

Система имеет множество решений вида вида $x=\begin{pmatrix}
C\\ 
-\frac{1}{2}C
\end{pmatrix}$, следовательно собственному значению $\lambda_2=2$ соответствует множество собственных векторов $x=\begin{pmatrix}
C\\ 
-\frac{1}{2}C
\end{pmatrix}$, где $C\neq0$.

In [1]:
import numpy as np

A = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(A)

print(f'Матрица A:\n{A}')
print(f'Собственные значения numpy:\n{w}')
print(f'Собственные векторы numpy:\n{v}')

print(f'\n------------------------------------\n')

x1=np.array([1, -2/3])
print(f'Наш собственный вектор x1:\n{x1}')
print(f'Проверка x1 (A*x1=3*x1):\n{A.dot(x1)}={3*x1}')

print(f'\n------------------------------------\n')

x2=np.array([1, -1/2])
print(f'Наш собственный вектор x2:\n{x2}')
print(f'Проверка x2 (A*x2=2*x2):\n{A.dot(x2)}={2*x2}')

Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения numpy:
[2. 3.]
Собственные векторы numpy:
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]

------------------------------------

Наш собственный вектор x1:
[ 1.         -0.66666667]
Проверка x1 (A*x1=3*x1):
[ 3. -2.]=[ 3. -2.]

------------------------------------

Наш собственный вектор x2:
[ 1.  -0.5]
Проверка x2 (A*x2=2*x2):
[ 2. -1.]=[ 2. -1.]


### __Ответ:__ cобственные значения $3$, $2$; cобственные векторы $\begin{pmatrix}
C\\ 
-\frac{2}{3}C
\end{pmatrix}$, где $C\neq0$, $\begin{pmatrix}
C\\ 
-\frac{1}{2}C
\end{pmatrix}$, где $C\neq0$.

### __2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

### Показать, что __любой__ вектор является для него собственным.

### __Решение:__

Найдем собственные значения линейного оператора, составив и решив характеристическое уравнение:

### $$\begin{vmatrix}
-1-\lambda & 0\\ 
0 & -1-\lambda
\end{vmatrix} = 0,$$

### $$(-1-\lambda)^2=0,$$

### $$\lambda_{1,2}=-1.$$

Теперь найдем собственные векторы:

### $$\begin{cases}
ax_{1}+bx_{2}=\lambda x_{1}, \\
cx_{1}+dx_{2}=\lambda x_{2}.
\end{cases}$$ 

### $$\begin{cases}
-x_{1}=-x_{1}, \\
-x_{2}=-x_{2}.
\end{cases}$$ 

Система имеет множество решений, а значит любой ненулевой вектор является собственным вектором оператора.

### __3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

### Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

### __Решение:__

Предположим, что вектор $x$ является собственным вектором заданного линейного оператора, тогда должно существовать некоторое вещественное число $\lambda$, при котором

### $$\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}
\begin{pmatrix}
1\\ 
1 
\end{pmatrix}=
\lambda
\begin{pmatrix}
1\\ 
1
\end{pmatrix}.
$$

Из этого будет следовать, что 

### $$\begin{cases}
1+1=1\cdot\lambda \\ 
-1+3 =1\cdot \lambda
\end{cases}
\Rightarrow
\begin{cases}
\lambda=2\\ 
\lambda=2
\end{cases}.$$

Таким образом, вектор $x=(1,1)$ является собственным вектором линейного оператора, заданного матрицей $A$, и его собственное значение составляет $\lambda=2.$

In [2]:
A = np.array([[1, 1], [-1, 3]])
w, v = np.linalg.eig(A)

print(f'Матрица A:\n{A}')
print(f'Собственные значения numpy:\n{w}')
print(f'Собственные векторы numpy:\n{v}')

Матрица A:
[[ 1  1]
 [-1  3]]
Собственные значения numpy:
[2.00000002 1.99999998]
Собственные векторы numpy:
[[ 0.70710677 -0.70710679]
 [ 0.70710679 -0.70710677]]


### __Ответ:__ является.

### __4.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}.$$

### Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

### __Решение:__

Предположим, что вектор $x$ является собственным вектором заданного линейного оператора. Аналогично методике из предыдущего примера получим:

$$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}
\begin{pmatrix}
3\\
-3\\
-4
\end{pmatrix}=
\lambda
\begin{pmatrix}
3\\
-3\\
-4
\end{pmatrix}
$$

$$\Rightarrow
\begin{cases}
3\lambda=-9\\ 
-3\lambda=9\\
-4\lambda=-12
\end{cases}
\Rightarrow
\begin{cases}
\lambda=-3\\ 
\lambda=-3\\
\lambda=3
\end{cases}.$$

Такая система не имеет смысла, следовательно, вектор $x=(3,-3, -4)$ не является собственным вектором линейного оператора, заданного матрицей $A$.

In [3]:
A = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
w, v = np.linalg.eig(A)

print(f'Матрица A:\n{A}')
print(f'Собственные значения numpy:\n{w}')
print(f'Собственные векторы numpy:\n{v}')

Матрица A:
[[0 3 0]
 [3 0 0]
 [0 0 3]]
Собственные значения numpy:
[ 3. -3.  3.]
Собственные векторы numpy:
[[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]


### __Ответ:__ не является.