# Урок 4

# Системы линейных уравнений. Часть 2

### __1.__ Решить систему уравнений методом Крамера:

###   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
###   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

### __Решение:__

### а)

In [1]:
import numpy as np

A = np.array([[1, -2], [3, -4]])
detA = np.linalg.det(A)
print(f'Матрица A:\n{A}')
print(f'Определитель матрицы A:\n{detA}')

A_1 = np.array([[1, -2], [7, -4]])
detA_1 = np.linalg.det(A_1)
print(f'Определитель матрицы A1:\n{detA_1}')
A_2 = np.array([[1, 1], [3, 7]])
detA_2 = np.linalg.det(A_2)
print(f'Определитель матрицы A2:\n{detA_2}')

x = np.array([[detA_1/detA, detA_2/detA]]).T
print(f'Вектор x:\n{x}')
print(f'Проверка, Ax:\n{A.dot(x)}=b')

Матрица A:
[[ 1 -2]
 [ 3 -4]]
Определитель матрицы A:
2.0000000000000004
Определитель матрицы A1:
9.999999999999998
Определитель матрицы A2:
3.999999999999999
Вектор x:
[[5.]
 [2.]]
Проверка, Ax:
[[1.]
 [7.]]=b


In [2]:
A = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
detA = np.linalg.det(A)
print(f'Матрица A:\n{A}')
print(f'Определитель матрицы A:\n{detA}')

A_1 = np.array([[10, -1, 5], [-2, 1, -3], [1, 4, 1]])
detA_1 = np.linalg.det(A_1)
print(f'Определитель матрицы A1:\n{detA_1}')
A_2 = np.array([[2, 10, 5], [1, -2, -3], [2, 1, 1]])
detA_2 = np.linalg.det(A_2)
print(f'Определитель матрицы A2:\n{detA_2}')
A_3 = np.array([[2, -1, 10], [1, 1, -2], [2, 4, 1]])
detA_3 = np.linalg.det(A_3)
print(f'Определитель матрицы A3:\n{detA_3}')

x = np.array([[detA_1/detA, detA_2/detA, detA_3/detA]]).T
print(f'Вектор x:\n{x}')
print(f'Проверка, Ax:\n{A.dot(x)}=b')

Матрица A:
[[ 2 -1  5]
 [ 1  1 -3]
 [ 2  4  1]]
Определитель матрицы A:
42.99999999999998
Определитель матрицы A1:
86.00000000000004
Определитель матрицы A2:
-43.000000000000014
Определитель матрицы A3:
43.0
Вектор x:
[[ 2.]
 [-1.]
 [ 1.]]
Проверка, Ax:
[[10.]
 [-2.]
 [ 1.]]=b


### __Ответ:__ a) $x=\begin{pmatrix}
5 \\ 
2 
\end{pmatrix}$; б) $x=\begin{pmatrix}
2 \\ 
-1 \\
1
\end{pmatrix}$

### __2*.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

###   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
###   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

### __Решение:__

### а)

Начнем прямой ход метода Гаусса. Для этого домножим первую строку на $2$ и вычтем ее из второго уравнения. При этом запишем в матрицу $L$ на место элемента $l_{21}$ значение $2$. Затем нам нужно вычесть из третьего уравнения первое, домноженное на $3$. Значит, в матрицу $L$ запишем $l_{31}=3$. 

Матрица коэффициентов будет иметь вид

### $$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 20 & 18
\end{pmatrix},$$

а матрица $L$ —

### $$\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & l_{32} & 1
\end{pmatrix}.$$

Далее умножим вторую строку на $4$ и вычтем ее из третьей. При этом в матрицу $L$ на место $l_{32}$ запишем $4$.

В итоге получим

### $$U=\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix},$$

### $$L=\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}.$$

### б)

Домножим первую строку на $2$ и вычтем ее из второй. При этом запишем в матрицу $L$ на место элемента $l_{21}$ значение $2$. Затем нам нужно вычесть из третьей строки первую, домноженную на $3$. Значит, в матрицу $L$ запишем $l_{31}=3$. И, наконец, из четвертой строки вычтем первую, домноженную на $4$, в матрицу $L$ запишем $l_{41}=4$.

Матрица коэффициентов будет иметь вид

### $$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 15 & 23 & 6\\
0 & 18 & 45 & 17
\end{pmatrix},$$

а матрица $L$ —

### $$\begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & l_{32} & 1 & 0 \\ 
4 & l_{42} & l_{43} & 1
\end{pmatrix}.$$

Далее умножим вторую строку на $5$ и вычтем ее из третьей. При этом в матрицу $L$ на место $l_{32}$ запишем $5$. Затем умножим вторую строку на $6$ и вычтем ее из четвертой. При этом в матрицу $L$ на место $l_{42}$ запишем $6$.

Матрица коэффициентов будет иметь вид

### $$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 21 & 11
\end{pmatrix},$$

а матрица $L$ —

### $$\begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & 5 & 1 & 0 \\ 
4 & 6 & l_{43} & 1
\end{pmatrix}.$$

Далее умножим третью строку на $7$ и вычтем ее из четвертой. При этом в матрицу $L$ на место $l_{43}$ запишем $7$.

В итоге получим

### $$U=\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 0 & 4
\end{pmatrix},$$

### $$L=\begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & 5 & 1 & 0 \\ 
4 & 6 & 7 & 1
\end{pmatrix}.$$

### __Ответ:__ а) $L=\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}$; б) $L=\begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & 5 & 1 & 0 \\ 
4 & 6 & 7 & 1
\end{pmatrix}$.

### __3*.__ Решить систему линейных уравнений методом $LU$-разложения

### $$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

### __Решение:__

Матрица коэффициентов $A$ будет иметь вид

### $$\begin{pmatrix}
2 & 1 & 3 \\ 
11 & 7 & 5 \\ 
9 & 8 & 4
\end{pmatrix}.$$

Начнем прямой ход метода Гаусса. Для этого домножим первую строку на $11/2$ и вычтем ее из второго уравнения. При этом запишем в матрицу $L$ на место элемента $l_{21}$ значение $11/2$. Затем нам нужно вычесть из третьего уравнения первое, домноженное на $9/2$. Значит, в матрицу $L$ запишем $l_{31}=9/2$. 

Матрица коэффициентов будет иметь вид

### $$\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 3/2 & -23/2 \\ 
0 & 7/2 & -19/2
\end{pmatrix},$$

а матрица $L$ —

### $$\begin{pmatrix}
1 & 0 & 0 \\ 
11/2 & 1 & 0 \\ 
9/2 & l_{32} & 1
\end{pmatrix}.$$

Далее умножим вторую строку на $7/3$ и вычтем ее из третьей. При этом в матрицу $L$ на место $l_{32}$ запишем $7/3$.

В итоге получим

### $$U=\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 3/2 & -23/2 \\ 
0 & 0 & 52/3
\end{pmatrix},$$

### $$L=\begin{pmatrix}
1 & 0 & 0 \\ 
11/2 & 1 & 0 \\ 
9/2 & 7/3 & 1
\end{pmatrix}.$$

Решим теперь систему 

### $$Ly=b:$$

### $$\begin{cases}
y_{1}=1, \\
11/2y_{1}+y_{2}=-6, \\
9/2y_{1}+7/3y_{2}+y_{3}=-5.
\end{cases}$$

### $$y_{1}=1,$$

### $$y_{2}=-23/2,$$

### $$y_{3}=52/3.$$

И затем систему

### $$Ux=y:$$

### $$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1, \\
3/2x_{2}-23/2x_{3}=-23/2, \\
52/3x_{3}=52/3.
\end{cases}$$

### $$x_{3}=1,$$

### $$x_{2}=0,$$

### $$x_{1}=-1.$$

Произведем проверку, подставив полученные значения переменных в исходную систему:

### $$\begin{cases}
2\cdot(-1)+3\cdot1=1 \\
11\cdot(-1)+5\cdot1=-6 \\
9\cdot(-1)+4\cdot1=-5
\end{cases}$$

Таким образом, найденное решение верно.

### __Ответ:__ $x=\begin{pmatrix}
-1 \\ 
0 \\
1
\end{pmatrix}$

### __4*.__ Решить систему линейных уравнений методом Холецкого

### $$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

### __Решение:__

In [3]:
A = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
w, v = np.linalg.eig(A)

print(f'Матрица A:\n{A}')
print(f'Собственные значения numpy:\n{w}')

Матрица A:
[[ 81 -45  45]
 [-45  50 -15]
 [ 45 -15  38]]
Собственные значения numpy:
[134.72475295   4.55103023  29.72421681]


Матрица $A$ симметричная и положительно определенная.

Произведем разложение на $LL^{T}$:

### $$l_{11}=\sqrt{a_{11}}=9,$$

### $$l_{21}=\frac{a_{21}}{l_{11}}=-5,$$

### $$l_{31}=\frac{a_{31}}{l_{11}}=5,$$

### $$l_{22}=\sqrt{a_{22}-l_{21}^{2}}=\sqrt{50 - 25}=5,$$

### $$l_{32}=\frac{1}{l_{22}}\left ( a_{32}-l_{21}l_{31} \right)=\frac{1}{5}\left ( -15 + 5\cdot 5 \right )=2,$$

### $$l_{33}=\sqrt{a_{33}-l_{31}^{2}-l_{32}^{2}}=\sqrt{38-25-4}=3.$$



Получили матрицу 

### $$L = \begin{pmatrix}
9 & 0 & 0 \\ 
-5 & 5 & 0 \\ 
5 & 2 & 3
\end{pmatrix}, 
\; \; 
L^{T} = \begin{pmatrix}
9 & -5 & 5 \\ 
0 & 5 & 2 \\ 
0 & 0 & 3
\end{pmatrix}.$$

Решим систему $Ly=b:$

### $$\begin{cases}
9y_{1}=531, \\
-5y_{1}+5y_{2}=-460, \\
5y_{1}+2y_{2}+3y_{3}=193.
\end{cases}$$

### $$y_{1}=59,$$

### $$y_{2}=-33,$$

### $$y_{3}=-12.$$

И решим систему $L^{T}x=y:$

### $$\begin{cases}
9x_{1}-5x_{2}+5x_{3}=59, \\
5x_{2}+2x_{3}=-33, \\
3x_{3}=-12.
\end{cases}$$

### $$x_{3}=-4,$$

### $$x_{2}=-5,$$

### $$x_{1}=6.$$

In [4]:
x = np.array([[6, -5, -4]]).T
print(f'Вектор x:\n{x}')
print(f'Проверка, Ax:\n{A.dot(x)}=b')

Вектор x:
[[ 6]
 [-5]
 [-4]]
Проверка, Ax:
[[ 531]
 [-460]
 [ 193]]=b


### __Ответ:__ $x=\begin{pmatrix}
6 \\ 
-5 \\
-4
\end{pmatrix}$

### __5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

### __Решение:__

In [5]:
def A_to_LU(a):
    lu = np.matrix(np.zeros([a.shape[0], a.shape[1]]))
    n = a.shape[0]
    for k in range(n):
        for j in range(k, n):
            lu[k, j] = a[k, j] - lu[k, :k] * lu[:k, j]
        for i in range(k + 1, n):
            lu[i, k] = (a[i, k] - lu[i, : k] * lu[: k, k]) / lu[k, k]
    return lu

def get_L(lu):
    L = lu.copy()
    for i in range(L.shape[0]):
        L[i, i] = 1
        L[i, i+1 :] = 0
    return L

def get_U(lu):
    U = lu.copy()
    for i in range(1, U.shape[0]):
        U[i, :i] = 0
    return U

def get_x(lu, b):
    y = np.matrix(np.zeros([lu.shape[0], 1]))
    for i in range(y.shape[0]):
        y[i, 0] = b[i, 0] - lu[i, :i] * y[:i]
    
    x = np.matrix(np.zeros([lu.shape[0], 1]))
    for i in range(1, x.shape[0] + 1):
        x[-i, 0] = (y[-i] - lu[-i, -i:] * x[-i:, 0] )/ lu[-i, -i]
    return x

In [6]:
A = np.matrix(np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]]))
b = np.matrix(np.array([[531, -460, 193]]).T)
print(f'Матрица A:\n{A}')
print(f'Вектор b:\n{b}')

LU = A_to_LU(A)
L = get_L(LU)
U = get_U(LU)

print(f'Матрица LU:\n{LU}')
print(f'Матрица L:\n{L}')
print(f'Матрица U:\n{U}')
print(f'Матрица L*U:\n{L.dot(U)}=A')

print(f'Вектор х:\n{get_x(LU, b)}')

Матрица A:
[[ 81 -45  45]
 [-45  50 -15]
 [ 45 -15  38]]
Вектор b:
[[ 531]
 [-460]
 [ 193]]
Матрица LU:
[[ 81.         -45.          45.        ]
 [ -0.55555556  25.          10.        ]
 [  0.55555556   0.4          9.        ]]
Матрица L:
[[ 1.          0.          0.        ]
 [-0.55555556  1.          0.        ]
 [ 0.55555556  0.4         1.        ]]
Матрица U:
[[ 81. -45.  45.]
 [  0.  25.  10.]
 [  0.   0.   9.]]
Матрица L*U:
[[ 81. -45.  45.]
 [-45.  50. -15.]
 [ 45. -15.  38.]]=A
Вектор х:
[[ 6.]
 [-5.]
 [-4.]]
